# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vidroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidroom',
            name='public_id',
            field=models.TextField(default=uuid.uuid4),
        ),
    ]
