# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidroom',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='vidroom',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
