# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidroom', '0004_auto_20160909_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_time_at',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vidroom',
            name='public_id',
            field=models.TextField(default='<function uuid4 at 0x7f51bba7be18>'),
        ),
    ]
