# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidroom', '0005_auto_20160909_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vidroom',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='vidroom',
            name='start_at',
        ),
        migrations.AlterField(
            model_name='vidroom',
            name='public_id',
            field=models.TextField(default='<function uuid4 at 0x7f421e733e18>'),
        ),
        migrations.AddField(
            model_name='playlistentry',
            name='vidroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidroom.VidRoom'),
        ),
    ]
