# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidroom', '0006_auto_20160912_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidroom',
            name='public_id',
            field=models.TextField(default='<function uuid4 at 0x7f488e447e18>'),
        ),
    ]
